sudo: required
dist: trusty

language: cpp


compiler: gcc

before_install: 
    #    - sudo apt-get -qq udpate
    - sudo apt-get install -y lib32ncurses5 lib32bz2-1.0 lib32z1 libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev curl 
    
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
script:
 - curl -C- https://launchpadlibrarian.net/287101520/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2 -o /tmp/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2
 - sudo tar -jxf /tmp/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2 -C /usr/local
 - pwd
 - ls
 - autoreconf -i 
 - mkdir build
 - cd build
 - PATH=/usr/local/:$PATH ../configure
 - PATH=/usr/local/:$PATH make
 - PATH=/usr/local/:$PATH make qemu